name: Corepermission: 

author: 0Pink, x1D
description: Core plugin for various utilities
main: pink.core.Core
api-version: '1.21'

commands:
  announce:
    description: Broadcast a message to everyone
    usage: /announce <message>
    permission: pink.announce
    aliases: [bc, broadcast]secretagentman:
    description: runic.sam
    aliases: [sam, spy]

permissions:
  pink.announce:
    description: Allows /announce
    default: op
